---
title: "Ocean acidification in the continental margin off Portugal: filling gaps with old data"
author: "Nils Lucas Jacobsen"
date: "`r format(Sys.time(), '%d %B, %Y')`"  # With Sys.Date it updates automatically
output: 
  html_document:
    toc: yes
    toc_float: yes
    toc_depth: 5
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.align = "center")
```

# PM trends step 0 - Packages
```{r installing and loading packages}

# This step installs packages if needed
list.of.packages <- c("R.matlab", "rlist", "tidyverse", "readxl", "marmap", "seacarb", "xlsx", "reshape2", "readr", "lubridate")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

# Load packages
library(R.matlab)
library(rlist)
library(tidyverse)
library(readxl)
library(marmap)
library(seacarb)
library(xlsx)
library(reshape2)
library(readr)
library(lubridate)
```

# PM trends step 1 - Preparation, carbon computations, and preliminary analysis
```{r Loading and filtering data & defining study area}

A <- readMat('GLODAPv2.2020_Atlantic_Ocean.mat')
# Keep the expocodes and their correspondence with G2cruise (expocodeno)
expocodes <- data.frame(); expocodes <- as.data.frame(unlist(A$expocode))
expocodes[, 2] <- as.data.frame(unlist(A$expocodeno))
names(expocodes) <- c("expocode", "expocodeno")
A <- A %>% list.remove(c("expocode", "expocodeno")) %>% as.data.frame()

ABasin <- data.frame(lon = c(-13, -7), lat = c(36, 42))  # Defining the geographical region

# Filter for geographical area, remove NAs in salinity and potential temperature, and add data soucre
A <- A %>%
  filter(G2latitude >= (min(ABasin$lat)) & G2latitude <= (max(ABasin$lat))) %>%
  filter(G2longitude >= (min(ABasin$lon)) & G2longitude <= (max(ABasin$lon))) %>%
  mutate_all(.funs = funs(ifelse(. == "NaN", NA, .))) %>%
  filter((!is.na(G2salinity))) %>%
  filter((!is.na(G2theta))) %>%
  mutate(source = "GLODAP")
```

```{r Layer separation, eval = FALSE, echo=FALSE}

# A <- A %>%
#   mutate(layer = ifelse(G2pressure >= 100 & G2sigma0 <= 27.2, "NACW",
#                       ifelse(G2sigma0 > 27.2 & G2sigma1 <= 32.35,"MW",
#                              ifelse(G2sigma1 > 32.35 & G2sigma2 <= 37, "LSW",
#                                     ifelse(G2sigma2 > 37, "NADW", NA))))) %>%
#   filter(!is.na(layer))  # Delete the NA values in layer (surface points)
# 
# ord <- c("NACW", "MW", "LSW", "NADW")
# A$layer <- factor(A$layer, levels = ord)
```
## Carbon computations

```{r Carbon computations}

A <- A %>%  # Adding flags for seacarb
  mutate(flag = ifelse(G2talkf == 2 & G2tco2f == 2, 15,  # Flag 15 Alk & DIC
                     ifelse(G2talkf == 2 & G2tco2f == 0 & G2phtsinsitutpf == 2, 8,  # Flag 8 pH & Alk
                            ifelse(G2talkf == 0 & G2tco2f == 2 & G2phtsinsitutpf == 2, 9, NA))))  # Flag 9 pH & DIC
 
A <- bind_cols(A[, 1:ncol(A)-1],  # To delete the flag column
                     carb(flag = A$flag, 
                          var1 = ifelse(A$flag == 15, A$G2talk / 10^6, 
                                      ifelse(A$flag == 9, A$G2phtsinsitutp,
                                             ifelse(A$flag == 8, A$G2phtsinsitutp, NA))),
                          var2 = ifelse(A$flag == 15, A$G2tco2 / 10^6, 
                                      ifelse(A$flag == 9, A$G2tco2 / 10^6,
                                             ifelse(A$flag == 8, A$G2talk / 10^6, NA))),
                          A$G2salinity, 
                          A$G2theta, 
                          A$G2pressure / 10,  # Pressure in bar!
                          Patm = 1.0, 
                          Pt = A$G2phosphate / 10^6,  # Nutrients in mols/Kg
                          Sit = A$G2silicate / 10^6,
                          pHscale = "T", kf = "pf", k1k2 = "l", ks = "d", b = "u74"))

A <- mutate(A, xcCO3 = CO3 - (CO3 / OmegaAragonite))  # Compute xcCO3

A <- filter(A, !is.na(flag))
```
## Add country & dates
```{r Adding country & dates}

wtf = expocodes[expocodes$expocodeno %in% sort(unique(A$G2cruise)), ]
wtf <- rename(wtf, G2cruise = expocodeno)  # Rename to ease the future join
A <- full_join(A, wtf)
rm(wtf)  # Cleaning

# Adding country with https://vocab.ices.dk/ ICES codes (seen in Olsen 2016, GLODAP paper)
A$country = "Spain"
A$country[A$G2cruise %in% c(25, 58, 64)] = "Germany"
A$country[A$G2cruise %in% c(237)] = "USA"
A$country[A$G2cruise %in% c(368, 392, 393, 394, 395, 1047)] = "France"
A$country[A$G2cruise %in% c(673)] = "Poland"
A$country[A$G2cruise %in% c(679, 683, 693)] = "UK"

A$country = reorder(A$country, A$country, function(x)-length(x))

# Add dates in GLODAP
A <- mutate(A, date = lubridate::ymd(paste(A$G2year, A$G2month, A$G2day, sep = "/")))
```

```{r Various preliminary plots}

  ggplot(A, aes(G2salinity, G2theta, color = as.character(round(G2sigma0, 1)))) +
    geom_point() +
    labs(color = "Sigma0") +
    xlab("Salinity") +
    ylab("Potential Temperature [°C]")

  ggplot(A, aes(x = country)) +
    geom_bar(aes(fill = country)) +
    scale_fill_brewer(type = "qual", palette = "Set1") +
    labs(x = "Country", y = "number of samples", 
         title = "Samples with carbon system in GLODAP near Portugal margin") +
    theme_minimal()
  
  ggplot(A, aes(x = G2year)) +
    geom_histogram(aes(fill = country), alpha = .5) +
    labs(x = "Year", y = "number of samples", 
         title = "Samples with carbon system in GLODAP near Portugal margin") +
    theme_minimal()
  
  A %>%
    filter(G2depth < 500) %>%
    ggplot(., aes(G2year, DIC * 10^6)) + 
    geom_point() + 
    geom_smooth(method = "lm")
  
  A %>%
    filter(G2depth < 500) %>%
    ggplot(., aes(G2year, pH)) + 
    geom_point() + 
    geom_smooth(method = "lm")
```

```{r Adding atmospheric data}

# Annual CO2 from Mauna Loa
url <- 'ftp://ftp.cmdl.noaa.gov/ccg/co2/trends/co2_annmean_mlo.txt'
file  <- tempfile()
download.file(url, file)
CO2 <- read.table(file, header = F)
CO2 <- CO2 %>%
  rename(year = V1, ppm = V2, uncertainty = V3) %>%
  mutate(site = "Mauna Loa") %>%
  select(-uncertainty)

CO2 <- rename(CO2, G2year = year)  # To match the name in G2
A <- left_join(A, CO2, by = "G2year")
```

# PM trends step 2 - Trend analysis pH
```{r CO2 data from OldPT and ICES after Neural Networks}

postNN_OldPT <- read_csv("postNN_CO2sys_OldPT.csv", na = "NaN")
postNN_OldPT <- postNN_OldPT %>% 
  mutate(source = "OldPT", country = "Portugal", xcCO3 = CO3out - (CO3out / OmegaARout))

postNN_ICES <- read_csv("postNN_CO2sys_ICESfiltered.csv", na = "NaN")
postNN_ICES <- postNN_ICES %>% 
  mutate(source = "ICES", country = "Portugal", xcCO3 = CO3out - (CO3out / OmegaARout))
```

```{r Computing mean pH with NN data}

only_pH_OldPT <- postNN_OldPT %>%  # A new data.frame from the loaded csv (and we keep it intact as postNN*)
  rename(G2year = year, pH = pHin) %>%  # Same name as in GLODAP
  filter(between(depth, 100, 500)) %>%  # To keep only the samples between 100 m and 500 m (both included)
  filter(pH > 7.9) %>%  # To delete some samples with very low pH (freshwater influence very likely)
  select(G2year, pH, source, country)  # Clean it all
  
# ICES data (The same for the ICES data)
only_pH_ICES <- postNN_ICES %>%
  rename(G2year = year, pH = pHin) %>%  # Same name as in GLODAP
  filter(between(PRESdb, 100, 500)) %>%  # To keep only the samples between 100 m and 500 m (both included)
  filter(pH > 7.9) %>%  # To delete some samples with very low pH (freshwater influence very likely)
  select(G2year, pH, source, country)  # Clean it all

# Again for the GLODAP data
only_pH_G2 <- A %>%
  filter(between(G2depth, 100, 500)) %>%
  select(G2year, pH, source, country)

# Joining the three data.farmes
dummy_pH <- full_join(only_pH_G2, only_pH_OldPT)
extended_pH <- full_join(dummy_pH, only_pH_ICES)  # 2-step join
rm(dummy_pH)

# Computing the mean pH per year
final_pH <- extended_pH %>%
  group_by(G2year) %>%
  summarise_at(vars(pH), mean, na.rm = TRUE)

# Computing the error of the mean pH per year
final_pH_error <- extended_pH %>%
  group_by(G2year) %>%
  summarise_at(vars(pH), sd, na.rm = TRUE)
```

```{r Linear model for pH}

RLMmodel_pH <- MASS::rlm(pH ~ G2year, data = final_pH, weights = (1 / final_pH_error$pH))

tableRLMmodel_pH <- summary(RLMmodel_pH)
trend_pH <- tableRLMmodel_pH[["coefficients"]][2, 1]  # This is the rate of change
etrend_pH <- tableRLMmodel_pH[["coefficients"]][2, 2]  # etrend stands for "error in the trend"

pvalue_pH <- pnorm(
  abs(
    broom::tidy(RLMmodel_pH)
    [2, "statistic", drop = TRUE]), lower.tail = FALSE) * 2
```

```{r Plot trend pH}

ggplot(final_pH, aes(G2year, pH)) +
  geom_jitter(data = extended_pH, aes(colour = source), alpha = .7, shape = 4, size = .3) +
  geom_smooth(method = MASS::rlm, color = "red", size = 2) +
  geom_point() +
  theme_minimal() +
  xlab("Year")
```

# PM trends step 3 - Trend analysis anthropogenic carbon
```{r Computing mean Cant per year}

Cant <- read.csv("Cant.csv")

only_Cant <- Cant %>% 
  filter(latitude >= (min(ABasin$lat)) & latitude <= (max(ABasin$lat))) %>%
  filter(longitude >= (min(ABasin$lon)) & longitude <= (max(ABasin$lon))) %>%
  mutate_all(.funs = funs(ifelse(. == "NaN", NA, .))) %>%
  filter(between(Depth, 100, 500)) %>%
  filter(!is.na(cAntPhiCt0ML)) %>%
  select(year, cAntPhiCt0ML)

final_Cant <- only_Cant %>%
  group_by(year) %>%
  summarise_at(vars(cAntPhiCt0ML), mean, na.rm = TRUE)

final_Cant_error <- only_Cant %>%
  group_by(year) %>%
  summarise_at(vars(cAntPhiCt0ML), sd, na.rm = TRUE)
```

```{r Linear model for Cant}

RLMmodel_Cant <- MASS::rlm(cAntPhiCt0ML ~ year, data = final_Cant, weights = (1 / final_Cant_error$cAntPhiCt0ML))

tableRLMmodel_Cant <- summary(RLMmodel_Cant)
trend_Cant <- tableRLMmodel_Cant[["coefficients"]][2, 1]  # This is the rate of change
etrend_Cant <- tableRLMmodel_Cant[["coefficients"]][2, 2]  # etrend stands for "error in the trend"

pvalue_Cant <- pnorm(
  abs(
    broom::tidy(RLMmodel_Cant)
    [2, "statistic", drop = TRUE]), lower.tail = FALSE) * 2
```

```{r Plot trend Cant}

ggplot(final_Cant, aes(year, cAntPhiCt0ML)) +
  geom_jitter(data = only_Cant, alpha = .7, shape = 4, size = .3) +
  geom_smooth(method = MASS::rlm, color = "red", size = 2) +
  geom_point() +
  theme_minimal() +
  xlab("Year") +
  ylab("Anthropogenic carbon [μmol/kg]")
```

# PM trends step 4 - Trend analysis xcCO3
```{r Computing mean xcCO3 per year}

only_xcCO3_G2 <- A %>% 
  filter(between(G2depth, 100, 500)) %>%
  filter(!is.na(xcCO3)) %>%
  select(G2year, xcCO3, source, country)

only_xcCO3_OldPT <- postNN_OldPT %>% 
  rename(G2year = year) %>%  # Same name as in GLODAP
  filter(between(depth, 100, 500)) %>%
  filter(!is.na(xcCO3)) %>%
  select(G2year, xcCO3, source, country)

only_xcCO3_ICES <- postNN_ICES %>% 
  rename(G2year = year) %>%  # Same name as in GLODAP
  filter(between(PRESdb, 100, 500)) %>%
  filter(!is.na(xcCO3)) %>%
  select(G2year, xcCO3, source, country)

# Joining the three data.farmes
dummy_xcCO3 <- full_join(only_xcCO3_G2, only_xcCO3_OldPT)
extended_xcCO3 <- full_join(dummy_xcCO3, only_xcCO3_ICES)  # 2-step join
rm(dummy_xcCO3)

final_xcCO3 <- extended_xcCO3 %>%
  group_by(G2year) %>%
  summarise_at(vars(xcCO3), mean, na.rm = TRUE)

final_xcCO3_error <- extended_xcCO3 %>%
  group_by(G2year) %>%
  summarise_at(vars(xcCO3), sd, na.rm = TRUE)
```

```{r Linear model for xcCO3}

RLMmodel_xcCO3 <- MASS::rlm(xcCO3 ~ G2year, data = final_xcCO3, weights = (1 / final_xcCO3_error$xcCO3))

tableRLMmodel_xcCo3 <- summary(RLMmodel_xcCO3)
trend_xcCo3 <- tableRLMmodel_xcCo3[["coefficients"]][2, 1]  # This is the rate of change
etrend_xcCo3 <- tableRLMmodel_xcCo3[["coefficients"]][2, 2]  # etrend stands for "error in the trend"

pvalue_xcCO3 <- pnorm(
  abs(
    broom::tidy(RLMmodel_xcCO3)
    [2, "statistic", drop = TRUE]), lower.tail = FALSE) * 2
```

```{r Plot trend xcCO3}

ggplot(final_xcCO3, aes(G2year, xcCO3)) +
  geom_jitter(data = extended_xcCO3, aes(colour = source), alpha = .7, shape = 4, size = .3) +
  geom_smooth(method = MASS::rlm, color = "red", size = 2) +
  geom_point() +
  theme_minimal() +
  xlab("Year")
```
# PM trends step 5 - Plots
```{r Map with stations}

t0 <- Sys.time()

stations <- A %>%
  filter(!is.na(xcCO3)) %>%
  select(G2longitude, G2latitude, G2year) %>%
  distinct(G2longitude, G2latitude, .keep_all = TRUE)

# Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : argument is of length zero
m <- getNOAA.bathy(lon1 = ABasin[1, 1] - 4, lon2 = ABasin[2, 1] + 5,  # -4 and +5 what does it mean?
                     lat1 = ABasin[1, 2] -5 , lat2 = ABasin[2, 2] + 3, resolution = 1)  # -5 and +3 # 1 is the smallest 

(basemap <- ggplot(m, aes(x = x, y = y)) + 
    coord_quickmap() +
    geom_raster(aes(fill = z)) +
    scale_fill_gradient2(low = "cadetblue1", mid = "white", high = "darkgreen", midpoint = 0, guide = F) +
    geom_contour(aes(z = z), breaks = c(-1000, -2000, -3000, -4000, -5000), colour = "gray", size = 0.5) +  # depth only between 100 and 500? what breaks?
    geom_contour(aes(z = z), breaks = c(0), colour = "black", size = 1) +
    # can I simply put the years from my data in?
    geom_point(data = stations[stations$G2year == 1981, ], aes(x = G2longitude, y = G2latitude),  
               color = "#fc9272", size = 4) + 
    geom_point(data = stations[stations$G2year == 1982, ], aes(x = G2longitude, y = G2latitude), 
               color = "#fb6a4a", size = 4) + 
    geom_point(data = stations[stations$G2year == 1984, ], aes(x = G2longitude, y = G2latitude), 
               color = "#ef3b2c", size = 4) + 
    geom_point(data = stations[stations$G2year == 1986, ], aes(x = G2longitude, y = G2latitude), 
               color = "#cb181d", size = 4) + 
    geom_point(data = stations[stations$G2year == 1988, ], aes(x = G2longitude, y = G2latitude), 
               color = "#99000d", size = 4) + 
    geom_point(data = stations[stations$G2year == 1989, ], aes(x = G2longitude, y = G2latitude), 
               color = "black", size = 4, shape = 17) +
    geom_point(data = stations[stations$G2year == 1991, ], aes(x = G2longitude, y = G2latitude), 
               color = "#1f78b4", size = 4, shape = 6) +
    geom_point(data = stations[stations$G2year == 1993, ], aes(x = G2longitude, y = G2latitude), 
               color = "chartreuse4", size = 4, shape = 9) +
    geom_point(data = stations[stations$G2year == 1997, ], aes(x = G2longitude, y = G2latitude), 
               color = "#fdbf6f", size = 4, shape = 8) +
    geom_point(data = stations[stations$G2year == 2001, ], aes(x = G2longitude, y = G2latitude),  # what other shapes should I use?
               color = "#6a3d9a", size = 4, shape = 18) +
    scale_shape_manual(values = seq(15, 25)) +  # what does this line do?
    # scale_x_continuous(expand = c(0,0), breaks = c(-30, -40, -50, -60),  # need to adjust 
    #                    labels = c("30ºW", "40ºW", "50ºW", "60ºW")) +
    # scale_y_continuous(expand = c(0,0), breaks = c(-30, -35, -40, -45, -50), 
    #                    labels = c("30ºS", "35ºS", "40ºS", "45ºS", "50ºS")) +
    # labs(x = "", y = "") +
    theme(
      panel.border = element_rect(colour = "black", fill = NA, size = 4),
      text = element_text(size = 28, colour = "black"),
      legend.title = element_blank())
)

savefigure = 0
if (savefigure) {
ggsave(filename = "PMtrends_map.pdf",
       plot = basemap, dpi = 300, width = 20, height = 23, units = "cm")
}

abrirfigura = 0
if (abrirfigura) {
  shell.exec("PMtrends_map.pdf")
}

print(paste("Done in", ceiling(Sys.time() - t0)))
```

